import {
  DashOutlined,
  FieldTimeOutlined,
  FileOutlined,
} from "@ant-design/icons";

import CourseImg from "../assets/images/course.jpg";

import {
  CourseIconImage,
  CourseHolderImage,
} from "../Pages/Student/Course/styled.Course";

export const STUDENT_COURSE = [
  {
    id: 1,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 2,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 3,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 4,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 5,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 6,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 7,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 8,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 9,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 10,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 11,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 12,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 13,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
  {
    id: 14,
    CourseIconImage: <CourseIconImage src={CourseImg} alt="" />,
    cardDashOutline: <DashOutlined />,
    CourseHolderImage: <CourseHolderImage src={CourseImg} alt="" />,
    lesson: <FileOutlined className="mr-1" />,
    hours: <FieldTimeOutlined className="mr-1" />,
  },
];
